[package]
name = "kernel"
version = "0.1.0"
authors = ["soveu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.6.0"
x86_64 = "0.12.2"

