[package]
name = "goodloader"
version = "0.1.0"
authors = ["soveu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
spin = "0.7"

[dependencies.elf]
version = "0.1"
path = "../elf"

